// These styles apply to every route in the application
import './globals.css'
import NotistackProvider from '../context/NotistackProvider'

export const metadata = {
  title: 'CONTACTOS',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body>
        <NotistackProvider>
          {children}
        </NotistackProvider>
      </body>
    </html>
  )
}
